In [17]:
import numpy as np

In [52]:
arr1 = np.array([1, 2, 3, 4, 9])
print(arr1)
arr2 = np.ones(5)
print(arr2)
arr3 = np.zeros(3)
print(arr3)

[1 2 3 4 9]
[1. 1. 1. 1. 1.]
[0. 0. 0.]


In [54]:
arr4 = np.concatenate([arr1, arr2, arr3])
arr4

array([1., 2., 3., 4., 9., 1., 1., 1., 1., 1., 0., 0., 0.])

In [56]:
arr4.sort()
arr4

array([0., 0., 0., 1., 1., 1., 1., 1., 1., 2., 3., 4., 9.])

In [58]:
print(arr1[2])
print(arr1[-3])

3
3


In [60]:
arr1[1:4]

array([2, 3, 4])

In [62]:
arr1 + arr2

array([ 2.,  3.,  4.,  5., 10.])

In [64]:
arr1 * -5

array([ -5, -10, -15, -20, -45])

In [70]:
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())

9
1
19
3.8


In [72]:
arr1[(arr1<1) | (arr1>3)]

array([4, 9])